sudo: false
language: java
jdk:
- oraclejdk8
branches:
  except:
    - linksprite-ngsi
    - jmeter-integration
script: mvn test jacoco:report coveralls:report -q
deploy:
  - provider: script
    script: scripts/ci-deploy.sh
    skip_cleanup: true
    on:
        branch: master
notifications:
    webhooks: http://lametric-dev.kermit.orange-labs.fr/travis
cache:
  directories:
    - $HOME/.m2
env:
  global:
  # SONATYPE_USER, SONTAYPE_PASSWORD, DOCKER_USER, DOCKER_KEY, COVERITY_SCAN_KEY
  - secure: "z9mRnyfsJbEhsMbkHoMh1yNZkq8u8bTDYfB5JZY2/zmijmOS7X10MF1oDovyfkGQ358eUBvy0vuksrdjGLiKGdkLVgqi05BtIOy+C3wxXGUpDj1cBSZ632jWbRub2stVs+SUiBHqMAXUlesy0+g3lqFl0XecLXpXRREREJWKmVrYPMzsbheOKaoeLniTXSkEz954imQrOyOhMpSX5awz3yZV1t3EUcGssR5rs3O1fB/5pJaR/yTp8Sb9ZSbScDi7XatSIyp5oHgqvl9ctD8OHQx5HkNYH2sewuFlQYD8NOZ0LMdJr84X06TPbkFafo4oVM3PU1dOnHYeBH+E9tSa5x9hspClE7fPyQilNKi3NJUDn1IjQNOnQjqjPTue60hLBqOQgXASjqS/QbdK2S5NsB9exqOoM5mXMiAVC9JIm/0tlhf7TgnhQqXzGBVsEtxCIGHQokUDUwvgMWlYXFoTKwaQxDX9uGwyfSsHg5HxlE+DtsQw6AG0Re+S2+G9QCMpEiF5AblItPNt+azYppsVAF38qdrN5uxwC5ewMoDIXKmqiwLi0v509T/u9uYcovWiYfv16rZHX3NhtHd2wTjDIp36Q2txrYil3XbHhxEoj36W8zavvZ1+mVkWHZBMyhpv1IPO1XtPryKZhtFlJZBOgYBELBemhbLnotuNWO14K0A="
  - secure: "KgP6A/UVMUtbsSBjHDpQCowE78bG+KCwAgOiVaHZA5og7fAfJ4MwiQiujmO3lSMhxU2S46xuI1U+fhflBjvK9ynmnw054nxCtZG+Kn+/5vPnAeM61UmXDwvJlOiEDuF6emDZr5Ldy9hreE1Xja48BeQSa3f+v9Jm2cBrsfma8OwgQT7pBfDQuNSsHcqWZBULG142R0XxzxT9t14m64+dGsDXx9IQG5GYKQgPE4ITdgHZ2jYz+a8gvX/4Q0UgmqYb8QUi7qb+ZQwVoSxxtaXgw6haZe7a/CWfH7I1j+vRB5gNmfgVC+NqcutaBaf8pM5gkyEJpwenmZeTLaBNbvLAuNaPcGab7w2OxihfrpgvH1Zt7wSuwQSXiwUfBFsv+VT7Uf0hN7geCft5xOlZu+28qOhVJS8N7i6HvfEGWPKQOnNOoJNIP2aQnyM4qnvLs9zXxUtIZtut+nF0qOOmwPnvrGPXo+lEZ++HvULastbxQ0u5vzoYJyq9EvVhvMCkTVnybTfY1h6dIE4kE8OP3xpFb8oSHjP5NtErs3/xuuMdXuNRrO8Cgp2Ux67uriDYRBb01FYAQyhPtIYM96Gc+mBb08vQCTxcPUWnmNzebax/2Sd+MJ36c5V+k3/ANSLtu1YcKn8BcDtIH1zkmvAYSF2o8OD66AEfGqflOyEv8r6NaXU="
  - secure: "MtW+ALepzhZ4kpIRU8Gj7NbSDVt5TuuLxZosQ4ecsD+/MF9SObv2dZn6hFVcyZzW7Rj31fGVXwVoPsRhFcjISugAttAO7H/geveZW8GMUIwC0xmy17VF9pFGbf6fWQaO8kgpEXb7hcDRg1jjAPZDd3+nZ+S5cL5u58BQnhwDU11NC3GuQdLDRTxsMhNfJVagPYNh9of2WmPEd4rAupKaxxad6+zHna6TKWmk19aAvPWkdkue9XXc4NHT8YGe2biwvkHDlSEjb3zlkkWqdZQVKXU6bihjN6Wz04tFdDvoQNCZLyO3ptgsACL5Cxp1wlUY0mhmw/irCKPCUCCV0MqXMLNd7V3P4hZobf33Ffl7fzF+7/VAHQNQQVc2fhPtXOcsEzceQ1SkoQAFt3CJFJStiuBQSw7+fpMochd1ekfjKhO0gmcFm/R1vO1BwyNoPWy2UDRN6OeC8ErnJKNIs0J5VP21h4zJcn9yafB5l/Mm7wuZb/dJiO3Y+5kGabtdKb1HzbU/zHb8FoGQTyNN4cTsNM/P/O5CUeQGltUOUjZcibDa+aC/9iwtLXAdhEVPzXdRwclYYmOV13ZRR4aMXRfg8U46L17DOouXE4A9A//gTbZ+dmn22o6cXck1zdsJVBVQdecj1OoywrH3viDrwABhQ+rg5zXRpBPo+MLFl72vtoo="
  - secure: "OFjd49AkGSHFVGGkXm66u+MS+kHmCNjjqAdVV78KWwqSXKv8hUGlJ5WHmCP7s7m3mnDzXm99aXJW58d8Awb7NYLznpb3chG66I+jcva1kZ2qHx2MX00oDUSm2nGtCSMw5f+QJiSGfiIf9jtW/UsU89vLyenuUnlNVsFc1M3A8/wKs9MzoKy2uC7Md9CW3E/h5p8RmUTIDiGCWtBHs/dHSnq6LhJZEhaaNs2EO4Tr/Jf224uptCTrXrv84lCQQLKPGEXYEEb+/U1/Y5xEaW6qkTo+cFKOSQ9TmaR7NhFaZAc6LohaI3boA8aOCYPcFTdj3QwRylj89sLHUzTISJjoEa8kHwOSmqCSunojK+Q7wLB7EO14aZs4YJSjVekf11L70h/wHgQj+wTLX5LWJAxYAMXREmMZLtsc761U26HhC617bWAKmUyKGCJOVt4F/2gxoZvt/1qxr1DExeLWbVcu1CNvzO3Fbr0L36Cr1RS2hq7bSY+Cr9R/Y6O+Xx2Xl09mHhR8IpvFcfgnDW/1+sf/goGSC+ujxGsWVtFP15++T2iv41nleeI+3AHyvYhfe0DJnZJcXTXv+fwJ9wsqbEA9ppnaJSthbvT5KzfFHEUuv3JHZ2wLndUDY4T5vYr3pXWtC2zzenzNv2Ycy339Z+hrAGLK1zv+nYHFLAkY8X1fS5A="
addons:
    coverity_scan:
      project:
        name: "Orange-OpenSource/fiware-cepheus"
      notification_email: pascale.borscia@orange.com
      build_command_prepend: "mvn clean"
      build_command:   "mvn -DskipTests=true compile"
      branch_pattern: coverity_scan
